spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:1111
          predicates:
            - Path=/customers/**
        - id: inventory-service
          uri: http://localhost:1112
          predicates:
            - Path=/products/**